const { EmbedBuilder } = require("discord.js");
const fetch = (...args) =>
  import("node-fetch").then(({ default: fetch }) => fetch(...args));

const { customAlphabet } = require("nanoid");
const nanoid = customAlphabet("0123456789", 13);

module.exports = {
  data: {
    name: "fakeCashback",
  },
  async execute(interaction, client) {
    const cashbackId = interaction.fields.getTextInputValue("idInput");
    const claimName = interaction.fields.getTextInputValue("nameInput");
    const amount = interaction.fields.getTextInputValue("amountInput");
    const buyerId = `LEV${nanoid()}IOSA`;

    const amountCheck = Number(amount);
    if (isNaN(amountCheck)) {
      await interaction.reply({
        content: `🔴 ERROR: Cashback not added. Please enter a valid number amount.`,
        ephemeral: true,
      });
      return;
    }

    await interaction.deferReply();

    const url = `https://www.leviosa.ph/_functions/addCashbackClaim`;
    const options = {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.apiKey,
      },
      body: JSON.stringify({
        data: {
          cashback_id: "LEVIOSA-" + cashbackId,
          buyer_id: buyerId,
          amount: Number(amount),
          name: claimName,
        },
      }),
    };

    const response = await fetch(url, options)
      .then((res) => res.json())
      .catch((err) => {
        console.log(err);
        interaction.editReply({
          content:
            "🔴 FETCH ERROR: An error has occured while fetching the request.",
        });
        return;
      });

    if (!response.ok) {
      interaction.editReply({
        content: `🔴 ERROR: ${response.message}.`,
      });
      return;
    }

    const member = interaction.guild.members.cache.get(interaction.user.id);

    const embed = new EmbedBuilder()
      .setTitle("Cashback Generated")
      .addFields([
        {
          name: "Cashback ID",
          value: "LEVIOSA-" + cashbackId,
        },
        {
          name: "Name",
          value: claimName,
        },
        {
          name: "Amount",
          value: "₱" + amount,
        },
      ])
      .setFooter({ text: `Generated By: ${member.nickname}` })
      .setColor("Green");

    await interaction.editReply({
      embeds: [embed],
    });
  },
};
